name: Main workflow

on:
  push:
    branches: [master]

jobs:
  merge-master-to-develop:
    name: Merge master -> rc1
    runs-on: ubuntu-latest

    steps:
        uses: tukasz/direct-merge-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: master
          target-branch: rc1
